// Package ml provides types for ML operations.
package ml

import (
	"time"

	"github.com/google/uuid"
)

// StrategyConstraints defines constraints for strategy generation
type StrategyConstraints struct {
	RiskLevel         string  // "low", "medium", "high"
	TargetReturn      float64 // Expected minimum return
	MaxDrawdownLimit  float64 // Maximum acceptable drawdown
	MinWinRate        float64 // Minimum win rate threshold
	MaxCandidates     int     // Maximum number of strategies to generate
	AggregatedFeatures map[string]float64
	TopMetrics         map[string]float64
}

// GeneratedStrategy represents a strategy generated by ML
type GeneratedStrategy struct {
	StrategyID       uuid.UUID
	Parameters       map[string]float64
	Confidence       float64
	ExpectedReturn   float64
	ExpectedSharpe   float64
	ExpectedWinRate  float64
	GeneratedAt      time.Time
}

// PredictionRequest represents a prediction request
type PredictionRequest struct {
	RaceID       uuid.UUID
	RunnerID     uuid.UUID
	StrategyID   uuid.UUID
	Features     []float64
	ModelVersion string
}

// PredictionResult represents a prediction response
type PredictionResult struct {
	RaceID              uuid.UUID
	RunnerID            uuid.UUID
	StrategyID          uuid.UUID
	Probability         float64
	Confidence          float64
	Recommendation      string
	ModelVersion        string
	PredictedAt         time.Time
}

// BacktestFilters defines filters for querying backtest results
type BacktestFilters struct {
	MinCompositeScore float64
	MaxCompositeScore float64
	StrategyID        *uuid.UUID
	StartDate         *time.Time
	EndDate           *time.Time
	Limit             int
}

// TrainingConfig defines configuration for model training
type TrainingConfig struct {
	ModelType            string
	Epochs               int
	BatchSize            int
	LearningRate         float64
	ValidationSplit      float64
	HyperparameterSearch bool
	NumTrials            int
	DataFilters          map[string]string // e.g., {"min_races": "100", "date_from": "2024-01-01"}
}

// TrainingStatus represents the status of a training job
type TrainingStatus struct {
	JobID       string
	Status      string // "pending", "running", "completed", "failed"
	ModelType   string
	SubmittedAt *time.Time
	StartedAt   *time.Time
	CompletedAt *time.Time
	Metrics     map[string]float64
	Error       string
}
