// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: ml_service.proto

package mlpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MLService_GetPrediction_FullMethodName          = "/mlservice.MLService/GetPrediction"
	MLService_EvaluateStrategy_FullMethodName       = "/mlservice.MLService/EvaluateStrategy"
	MLService_GetFeatures_FullMethodName            = "/mlservice.MLService/GetFeatures"
	MLService_HealthCheck_FullMethodName            = "/mlservice.MLService/HealthCheck"
	MLService_SubmitBacktestFeedback_FullMethodName = "/mlservice.MLService/SubmitBacktestFeedback"
	MLService_GenerateStrategy_FullMethodName       = "/mlservice.MLService/GenerateStrategy"
	MLService_BatchPredict_FullMethodName           = "/mlservice.MLService/BatchPredict"
)

// MLServiceClient is the client API for MLService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MLServiceClient interface {
	GetPrediction(ctx context.Context, in *PredictionRequest, opts ...grpc.CallOption) (*PredictionResponse, error)
	EvaluateStrategy(ctx context.Context, in *StrategyRequest, opts ...grpc.CallOption) (*StrategyResponse, error)
	GetFeatures(ctx context.Context, in *FeatureRequest, opts ...grpc.CallOption) (*FeatureResponse, error)
	HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthStatus, error)
	SubmitBacktestFeedback(ctx context.Context, in *BacktestFeedbackRequest, opts ...grpc.CallOption) (*BacktestFeedbackResponse, error)
	GenerateStrategy(ctx context.Context, in *StrategyGenerationRequest, opts ...grpc.CallOption) (*StrategyGenerationResponse, error)
	BatchPredict(ctx context.Context, in *BatchPredictionRequest, opts ...grpc.CallOption) (*BatchPredictionResponse, error)
}

type mLServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMLServiceClient(cc grpc.ClientConnInterface) MLServiceClient {
	return &mLServiceClient{cc}
}

func (c *mLServiceClient) GetPrediction(ctx context.Context, in *PredictionRequest, opts ...grpc.CallOption) (*PredictionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PredictionResponse)
	err := c.cc.Invoke(ctx, MLService_GetPrediction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLServiceClient) EvaluateStrategy(ctx context.Context, in *StrategyRequest, opts ...grpc.CallOption) (*StrategyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StrategyResponse)
	err := c.cc.Invoke(ctx, MLService_EvaluateStrategy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLServiceClient) GetFeatures(ctx context.Context, in *FeatureRequest, opts ...grpc.CallOption) (*FeatureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FeatureResponse)
	err := c.cc.Invoke(ctx, MLService_GetFeatures_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLServiceClient) HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthStatus)
	err := c.cc.Invoke(ctx, MLService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLServiceClient) SubmitBacktestFeedback(ctx context.Context, in *BacktestFeedbackRequest, opts ...grpc.CallOption) (*BacktestFeedbackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BacktestFeedbackResponse)
	err := c.cc.Invoke(ctx, MLService_SubmitBacktestFeedback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLServiceClient) GenerateStrategy(ctx context.Context, in *StrategyGenerationRequest, opts ...grpc.CallOption) (*StrategyGenerationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StrategyGenerationResponse)
	err := c.cc.Invoke(ctx, MLService_GenerateStrategy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLServiceClient) BatchPredict(ctx context.Context, in *BatchPredictionRequest, opts ...grpc.CallOption) (*BatchPredictionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchPredictionResponse)
	err := c.cc.Invoke(ctx, MLService_BatchPredict_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MLServiceServer is the server API for MLService service.
// All implementations must embed UnimplementedMLServiceServer
// for forward compatibility.
type MLServiceServer interface {
	GetPrediction(context.Context, *PredictionRequest) (*PredictionResponse, error)
	EvaluateStrategy(context.Context, *StrategyRequest) (*StrategyResponse, error)
	GetFeatures(context.Context, *FeatureRequest) (*FeatureResponse, error)
	HealthCheck(context.Context, *Empty) (*HealthStatus, error)
	SubmitBacktestFeedback(context.Context, *BacktestFeedbackRequest) (*BacktestFeedbackResponse, error)
	GenerateStrategy(context.Context, *StrategyGenerationRequest) (*StrategyGenerationResponse, error)
	BatchPredict(context.Context, *BatchPredictionRequest) (*BatchPredictionResponse, error)
	mustEmbedUnimplementedMLServiceServer()
}

// UnimplementedMLServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMLServiceServer struct{}

func (UnimplementedMLServiceServer) GetPrediction(context.Context, *PredictionRequest) (*PredictionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPrediction not implemented")
}
func (UnimplementedMLServiceServer) EvaluateStrategy(context.Context, *StrategyRequest) (*StrategyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EvaluateStrategy not implemented")
}
func (UnimplementedMLServiceServer) GetFeatures(context.Context, *FeatureRequest) (*FeatureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFeatures not implemented")
}
func (UnimplementedMLServiceServer) HealthCheck(context.Context, *Empty) (*HealthStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedMLServiceServer) SubmitBacktestFeedback(context.Context, *BacktestFeedbackRequest) (*BacktestFeedbackResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitBacktestFeedback not implemented")
}
func (UnimplementedMLServiceServer) GenerateStrategy(context.Context, *StrategyGenerationRequest) (*StrategyGenerationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateStrategy not implemented")
}
func (UnimplementedMLServiceServer) BatchPredict(context.Context, *BatchPredictionRequest) (*BatchPredictionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchPredict not implemented")
}
func (UnimplementedMLServiceServer) mustEmbedUnimplementedMLServiceServer() {}
func (UnimplementedMLServiceServer) testEmbeddedByValue()                   {}

// UnsafeMLServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MLServiceServer will
// result in compilation errors.
type UnsafeMLServiceServer interface {
	mustEmbedUnimplementedMLServiceServer()
}

func RegisterMLServiceServer(s grpc.ServiceRegistrar, srv MLServiceServer) {
	// If the following call panics, it indicates UnimplementedMLServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MLService_ServiceDesc, srv)
}

func _MLService_GetPrediction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PredictionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLServiceServer).GetPrediction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLService_GetPrediction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLServiceServer).GetPrediction(ctx, req.(*PredictionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLService_EvaluateStrategy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StrategyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLServiceServer).EvaluateStrategy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLService_EvaluateStrategy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLServiceServer).EvaluateStrategy(ctx, req.(*StrategyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLService_GetFeatures_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FeatureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLServiceServer).GetFeatures(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLService_GetFeatures_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLServiceServer).GetFeatures(ctx, req.(*FeatureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLServiceServer).HealthCheck(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLService_SubmitBacktestFeedback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BacktestFeedbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLServiceServer).SubmitBacktestFeedback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLService_SubmitBacktestFeedback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLServiceServer).SubmitBacktestFeedback(ctx, req.(*BacktestFeedbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLService_GenerateStrategy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StrategyGenerationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLServiceServer).GenerateStrategy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLService_GenerateStrategy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLServiceServer).GenerateStrategy(ctx, req.(*StrategyGenerationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLService_BatchPredict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchPredictionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLServiceServer).BatchPredict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLService_BatchPredict_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLServiceServer).BatchPredict(ctx, req.(*BatchPredictionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MLService_ServiceDesc is the grpc.ServiceDesc for MLService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MLService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mlservice.MLService",
	HandlerType: (*MLServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPrediction",
			Handler:    _MLService_GetPrediction_Handler,
		},
		{
			MethodName: "EvaluateStrategy",
			Handler:    _MLService_EvaluateStrategy_Handler,
		},
		{
			MethodName: "GetFeatures",
			Handler:    _MLService_GetFeatures_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _MLService_HealthCheck_Handler,
		},
		{
			MethodName: "SubmitBacktestFeedback",
			Handler:    _MLService_SubmitBacktestFeedback_Handler,
		},
		{
			MethodName: "GenerateStrategy",
			Handler:    _MLService_GenerateStrategy_Handler,
		},
		{
			MethodName: "BatchPredict",
			Handler:    _MLService_BatchPredict_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ml_service.proto",
}
