// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: ml_service.proto

package mlpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PredictionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RaceId        string                 `protobuf:"bytes,1,opt,name=race_id,json=raceId,proto3" json:"race_id,omitempty"`
	StrategyId    string                 `protobuf:"bytes,2,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	Features      []float64              `protobuf:"fixed64,3,rep,packed,name=features,proto3" json:"features,omitempty"`
	RunnerId      string                 `protobuf:"bytes,4,opt,name=runner_id,json=runnerId,proto3" json:"runner_id,omitempty"`
	ModelVersion  string                 `protobuf:"bytes,5,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictionRequest) Reset() {
	*x = PredictionRequest{}
	mi := &file_ml_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictionRequest) ProtoMessage() {}

func (x *PredictionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ml_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictionRequest.ProtoReflect.Descriptor instead.
func (*PredictionRequest) Descriptor() ([]byte, []int) {
	return file_ml_service_proto_rawDescGZIP(), []int{0}
}

func (x *PredictionRequest) GetRaceId() string {
	if x != nil {
		return x.RaceId
	}
	return ""
}

func (x *PredictionRequest) GetStrategyId() string {
	if x != nil {
		return x.StrategyId
	}
	return ""
}

func (x *PredictionRequest) GetFeatures() []float64 {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *PredictionRequest) GetRunnerId() string {
	if x != nil {
		return x.RunnerId
	}
	return ""
}

func (x *PredictionRequest) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

type PredictionResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	RaceId               string                 `protobuf:"bytes,1,opt,name=race_id,json=raceId,proto3" json:"race_id,omitempty"`
	PredictedProbability float64                `protobuf:"fixed64,2,opt,name=predicted_probability,json=predictedProbability,proto3" json:"predicted_probability,omitempty"`
	Confidence           float64                `protobuf:"fixed64,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	RunnerId             string                 `protobuf:"bytes,4,opt,name=runner_id,json=runnerId,proto3" json:"runner_id,omitempty"`
	Recommendation       string                 `protobuf:"bytes,5,opt,name=recommendation,proto3" json:"recommendation,omitempty"`
	ModelVersion         string                 `protobuf:"bytes,6,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PredictionResponse) Reset() {
	*x = PredictionResponse{}
	mi := &file_ml_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictionResponse) ProtoMessage() {}

func (x *PredictionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ml_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictionResponse.ProtoReflect.Descriptor instead.
func (*PredictionResponse) Descriptor() ([]byte, []int) {
	return file_ml_service_proto_rawDescGZIP(), []int{1}
}

func (x *PredictionResponse) GetRaceId() string {
	if x != nil {
		return x.RaceId
	}
	return ""
}

func (x *PredictionResponse) GetPredictedProbability() float64 {
	if x != nil {
		return x.PredictedProbability
	}
	return 0
}

func (x *PredictionResponse) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *PredictionResponse) GetRunnerId() string {
	if x != nil {
		return x.RunnerId
	}
	return ""
}

func (x *PredictionResponse) GetRecommendation() string {
	if x != nil {
		return x.Recommendation
	}
	return ""
}

func (x *PredictionResponse) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

type StrategyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StrategyId    string                 `protobuf:"bytes,1,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StrategyRequest) Reset() {
	*x = StrategyRequest{}
	mi := &file_ml_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StrategyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrategyRequest) ProtoMessage() {}

func (x *StrategyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ml_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrategyRequest.ProtoReflect.Descriptor instead.
func (*StrategyRequest) Descriptor() ([]byte, []int) {
	return file_ml_service_proto_rawDescGZIP(), []int{2}
}

func (x *StrategyRequest) GetStrategyId() string {
	if x != nil {
		return x.StrategyId
	}
	return ""
}

type StrategyResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StrategyId     string                 `protobuf:"bytes,1,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	CompositeScore float64                `protobuf:"fixed64,2,opt,name=composite_score,json=compositeScore,proto3" json:"composite_score,omitempty"`
	Recommendation string                 `protobuf:"bytes,3,opt,name=recommendation,proto3" json:"recommendation,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StrategyResponse) Reset() {
	*x = StrategyResponse{}
	mi := &file_ml_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StrategyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrategyResponse) ProtoMessage() {}

func (x *StrategyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ml_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrategyResponse.ProtoReflect.Descriptor instead.
func (*StrategyResponse) Descriptor() ([]byte, []int) {
	return file_ml_service_proto_rawDescGZIP(), []int{3}
}

func (x *StrategyResponse) GetStrategyId() string {
	if x != nil {
		return x.StrategyId
	}
	return ""
}

func (x *StrategyResponse) GetCompositeScore() float64 {
	if x != nil {
		return x.CompositeScore
	}
	return 0
}

func (x *StrategyResponse) GetRecommendation() string {
	if x != nil {
		return x.Recommendation
	}
	return ""
}

type FeatureRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	BacktestResultId string                 `protobuf:"bytes,1,opt,name=backtest_result_id,json=backtestResultId,proto3" json:"backtest_result_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FeatureRequest) Reset() {
	*x = FeatureRequest{}
	mi := &file_ml_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeatureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureRequest) ProtoMessage() {}

func (x *FeatureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ml_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureRequest.ProtoReflect.Descriptor instead.
func (*FeatureRequest) Descriptor() ([]byte, []int) {
	return file_ml_service_proto_rawDescGZIP(), []int{4}
}

func (x *FeatureRequest) GetBacktestResultId() string {
	if x != nil {
		return x.BacktestResultId
	}
	return ""
}

type FeatureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Features      map[string]float64     `protobuf:"bytes,1,rep,name=features,proto3" json:"features,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeatureResponse) Reset() {
	*x = FeatureResponse{}
	mi := &file_ml_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeatureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureResponse) ProtoMessage() {}

func (x *FeatureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ml_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureResponse.ProtoReflect.Descriptor instead.
func (*FeatureResponse) Descriptor() ([]byte, []int) {
	return file_ml_service_proto_rawDescGZIP(), []int{5}
}

func (x *FeatureResponse) GetFeatures() map[string]float64 {
	if x != nil {
		return x.Features
	}
	return nil
}

type HealthStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthStatus) Reset() {
	*x = HealthStatus{}
	mi := &file_ml_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthStatus) ProtoMessage() {}

func (x *HealthStatus) ProtoReflect() protoreflect.Message {
	mi := &file_ml_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthStatus.ProtoReflect.Descriptor instead.
func (*HealthStatus) Descriptor() ([]byte, []int) {
	return file_ml_service_proto_rawDescGZIP(), []int{6}
}

func (x *HealthStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_ml_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_ml_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_ml_service_proto_rawDescGZIP(), []int{7}
}

type BacktestFeedbackRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StrategyId     string                 `protobuf:"bytes,1,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	CompositeScore float64                `protobuf:"fixed64,2,opt,name=composite_score,json=compositeScore,proto3" json:"composite_score,omitempty"`
	SharpeRatio    float64                `protobuf:"fixed64,3,opt,name=sharpe_ratio,json=sharpeRatio,proto3" json:"sharpe_ratio,omitempty"`
	Roi            float64                `protobuf:"fixed64,4,opt,name=roi,proto3" json:"roi,omitempty"`
	MaxDrawdown    float64                `protobuf:"fixed64,5,opt,name=max_drawdown,json=maxDrawdown,proto3" json:"max_drawdown,omitempty"`
	WinRate        float64                `protobuf:"fixed64,6,opt,name=win_rate,json=winRate,proto3" json:"win_rate,omitempty"`
	ProfitFactor   float64                `protobuf:"fixed64,7,opt,name=profit_factor,json=profitFactor,proto3" json:"profit_factor,omitempty"`
	TotalBets      int32                  `protobuf:"varint,8,opt,name=total_bets,json=totalBets,proto3" json:"total_bets,omitempty"`
	MlFeatures     map[string]float64     `protobuf:"bytes,9,rep,name=ml_features,json=mlFeatures,proto3" json:"ml_features,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	Method         string                 `protobuf:"bytes,10,opt,name=method,proto3" json:"method,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BacktestFeedbackRequest) Reset() {
	*x = BacktestFeedbackRequest{}
	mi := &file_ml_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BacktestFeedbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BacktestFeedbackRequest) ProtoMessage() {}

func (x *BacktestFeedbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ml_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BacktestFeedbackRequest.ProtoReflect.Descriptor instead.
func (*BacktestFeedbackRequest) Descriptor() ([]byte, []int) {
	return file_ml_service_proto_rawDescGZIP(), []int{8}
}

func (x *BacktestFeedbackRequest) GetStrategyId() string {
	if x != nil {
		return x.StrategyId
	}
	return ""
}

func (x *BacktestFeedbackRequest) GetCompositeScore() float64 {
	if x != nil {
		return x.CompositeScore
	}
	return 0
}

func (x *BacktestFeedbackRequest) GetSharpeRatio() float64 {
	if x != nil {
		return x.SharpeRatio
	}
	return 0
}

func (x *BacktestFeedbackRequest) GetRoi() float64 {
	if x != nil {
		return x.Roi
	}
	return 0
}

func (x *BacktestFeedbackRequest) GetMaxDrawdown() float64 {
	if x != nil {
		return x.MaxDrawdown
	}
	return 0
}

func (x *BacktestFeedbackRequest) GetWinRate() float64 {
	if x != nil {
		return x.WinRate
	}
	return 0
}

func (x *BacktestFeedbackRequest) GetProfitFactor() float64 {
	if x != nil {
		return x.ProfitFactor
	}
	return 0
}

func (x *BacktestFeedbackRequest) GetTotalBets() int32 {
	if x != nil {
		return x.TotalBets
	}
	return 0
}

func (x *BacktestFeedbackRequest) GetMlFeatures() map[string]float64 {
	if x != nil {
		return x.MlFeatures
	}
	return nil
}

func (x *BacktestFeedbackRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

type BacktestFeedbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	FeedbackId    string                 `protobuf:"bytes,3,opt,name=feedback_id,json=feedbackId,proto3" json:"feedback_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BacktestFeedbackResponse) Reset() {
	*x = BacktestFeedbackResponse{}
	mi := &file_ml_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BacktestFeedbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BacktestFeedbackResponse) ProtoMessage() {}

func (x *BacktestFeedbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ml_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BacktestFeedbackResponse.ProtoReflect.Descriptor instead.
func (*BacktestFeedbackResponse) Descriptor() ([]byte, []int) {
	return file_ml_service_proto_rawDescGZIP(), []int{9}
}

func (x *BacktestFeedbackResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BacktestFeedbackResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BacktestFeedbackResponse) GetFeedbackId() string {
	if x != nil {
		return x.FeedbackId
	}
	return ""
}

type StrategyGenerationRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RiskLevel          string                 `protobuf:"bytes,1,opt,name=risk_level,json=riskLevel,proto3" json:"risk_level,omitempty"` // "low", "medium", "high"
	TargetReturn       float64                `protobuf:"fixed64,2,opt,name=target_return,json=targetReturn,proto3" json:"target_return,omitempty"`
	MaxDrawdownLimit   float64                `protobuf:"fixed64,3,opt,name=max_drawdown_limit,json=maxDrawdownLimit,proto3" json:"max_drawdown_limit,omitempty"`
	MinWinRate         float64                `protobuf:"fixed64,4,opt,name=min_win_rate,json=minWinRate,proto3" json:"min_win_rate,omitempty"`
	MaxCandidates      int32                  `protobuf:"varint,5,opt,name=max_candidates,json=maxCandidates,proto3" json:"max_candidates,omitempty"`
	AggregatedFeatures map[string]float64     `protobuf:"bytes,6,rep,name=aggregated_features,json=aggregatedFeatures,proto3" json:"aggregated_features,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	TopMetrics         map[string]float64     `protobuf:"bytes,7,rep,name=top_metrics,json=topMetrics,proto3" json:"top_metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StrategyGenerationRequest) Reset() {
	*x = StrategyGenerationRequest{}
	mi := &file_ml_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StrategyGenerationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrategyGenerationRequest) ProtoMessage() {}

func (x *StrategyGenerationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ml_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrategyGenerationRequest.ProtoReflect.Descriptor instead.
func (*StrategyGenerationRequest) Descriptor() ([]byte, []int) {
	return file_ml_service_proto_rawDescGZIP(), []int{10}
}

func (x *StrategyGenerationRequest) GetRiskLevel() string {
	if x != nil {
		return x.RiskLevel
	}
	return ""
}

func (x *StrategyGenerationRequest) GetTargetReturn() float64 {
	if x != nil {
		return x.TargetReturn
	}
	return 0
}

func (x *StrategyGenerationRequest) GetMaxDrawdownLimit() float64 {
	if x != nil {
		return x.MaxDrawdownLimit
	}
	return 0
}

func (x *StrategyGenerationRequest) GetMinWinRate() float64 {
	if x != nil {
		return x.MinWinRate
	}
	return 0
}

func (x *StrategyGenerationRequest) GetMaxCandidates() int32 {
	if x != nil {
		return x.MaxCandidates
	}
	return 0
}

func (x *StrategyGenerationRequest) GetAggregatedFeatures() map[string]float64 {
	if x != nil {
		return x.AggregatedFeatures
	}
	return nil
}

func (x *StrategyGenerationRequest) GetTopMetrics() map[string]float64 {
	if x != nil {
		return x.TopMetrics
	}
	return nil
}

type StrategyGenerationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Strategies    []*GeneratedStrategy   `protobuf:"bytes,1,rep,name=strategies,proto3" json:"strategies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StrategyGenerationResponse) Reset() {
	*x = StrategyGenerationResponse{}
	mi := &file_ml_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StrategyGenerationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrategyGenerationResponse) ProtoMessage() {}

func (x *StrategyGenerationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ml_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrategyGenerationResponse.ProtoReflect.Descriptor instead.
func (*StrategyGenerationResponse) Descriptor() ([]byte, []int) {
	return file_ml_service_proto_rawDescGZIP(), []int{11}
}

func (x *StrategyGenerationResponse) GetStrategies() []*GeneratedStrategy {
	if x != nil {
		return x.Strategies
	}
	return nil
}

type GeneratedStrategy struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	StrategyId      string                 `protobuf:"bytes,1,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	Parameters      map[string]float64     `protobuf:"bytes,2,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	Confidence      float64                `protobuf:"fixed64,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	ExpectedReturn  float64                `protobuf:"fixed64,4,opt,name=expected_return,json=expectedReturn,proto3" json:"expected_return,omitempty"`
	ExpectedSharpe  float64                `protobuf:"fixed64,5,opt,name=expected_sharpe,json=expectedSharpe,proto3" json:"expected_sharpe,omitempty"`
	ExpectedWinRate float64                `protobuf:"fixed64,6,opt,name=expected_win_rate,json=expectedWinRate,proto3" json:"expected_win_rate,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GeneratedStrategy) Reset() {
	*x = GeneratedStrategy{}
	mi := &file_ml_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneratedStrategy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratedStrategy) ProtoMessage() {}

func (x *GeneratedStrategy) ProtoReflect() protoreflect.Message {
	mi := &file_ml_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratedStrategy.ProtoReflect.Descriptor instead.
func (*GeneratedStrategy) Descriptor() ([]byte, []int) {
	return file_ml_service_proto_rawDescGZIP(), []int{12}
}

func (x *GeneratedStrategy) GetStrategyId() string {
	if x != nil {
		return x.StrategyId
	}
	return ""
}

func (x *GeneratedStrategy) GetParameters() map[string]float64 {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *GeneratedStrategy) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *GeneratedStrategy) GetExpectedReturn() float64 {
	if x != nil {
		return x.ExpectedReturn
	}
	return 0
}

func (x *GeneratedStrategy) GetExpectedSharpe() float64 {
	if x != nil {
		return x.ExpectedSharpe
	}
	return 0
}

func (x *GeneratedStrategy) GetExpectedWinRate() float64 {
	if x != nil {
		return x.ExpectedWinRate
	}
	return 0
}

type BatchPredictionRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Predictions   []*SinglePredictionRequest `protobuf:"bytes,1,rep,name=predictions,proto3" json:"predictions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchPredictionRequest) Reset() {
	*x = BatchPredictionRequest{}
	mi := &file_ml_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchPredictionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchPredictionRequest) ProtoMessage() {}

func (x *BatchPredictionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ml_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchPredictionRequest.ProtoReflect.Descriptor instead.
func (*BatchPredictionRequest) Descriptor() ([]byte, []int) {
	return file_ml_service_proto_rawDescGZIP(), []int{13}
}

func (x *BatchPredictionRequest) GetPredictions() []*SinglePredictionRequest {
	if x != nil {
		return x.Predictions
	}
	return nil
}

type SinglePredictionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RaceId        string                 `protobuf:"bytes,1,opt,name=race_id,json=raceId,proto3" json:"race_id,omitempty"`
	RunnerId      string                 `protobuf:"bytes,2,opt,name=runner_id,json=runnerId,proto3" json:"runner_id,omitempty"`
	StrategyId    string                 `protobuf:"bytes,3,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	Features      []float64              `protobuf:"fixed64,4,rep,packed,name=features,proto3" json:"features,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SinglePredictionRequest) Reset() {
	*x = SinglePredictionRequest{}
	mi := &file_ml_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SinglePredictionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SinglePredictionRequest) ProtoMessage() {}

func (x *SinglePredictionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ml_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SinglePredictionRequest.ProtoReflect.Descriptor instead.
func (*SinglePredictionRequest) Descriptor() ([]byte, []int) {
	return file_ml_service_proto_rawDescGZIP(), []int{14}
}

func (x *SinglePredictionRequest) GetRaceId() string {
	if x != nil {
		return x.RaceId
	}
	return ""
}

func (x *SinglePredictionRequest) GetRunnerId() string {
	if x != nil {
		return x.RunnerId
	}
	return ""
}

func (x *SinglePredictionRequest) GetStrategyId() string {
	if x != nil {
		return x.StrategyId
	}
	return ""
}

func (x *SinglePredictionRequest) GetFeatures() []float64 {
	if x != nil {
		return x.Features
	}
	return nil
}

type BatchPredictionResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Predictions   []*SinglePredictionResponse `protobuf:"bytes,1,rep,name=predictions,proto3" json:"predictions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchPredictionResponse) Reset() {
	*x = BatchPredictionResponse{}
	mi := &file_ml_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchPredictionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchPredictionResponse) ProtoMessage() {}

func (x *BatchPredictionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ml_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchPredictionResponse.ProtoReflect.Descriptor instead.
func (*BatchPredictionResponse) Descriptor() ([]byte, []int) {
	return file_ml_service_proto_rawDescGZIP(), []int{15}
}

func (x *BatchPredictionResponse) GetPredictions() []*SinglePredictionResponse {
	if x != nil {
		return x.Predictions
	}
	return nil
}

type SinglePredictionResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	RaceId               string                 `protobuf:"bytes,1,opt,name=race_id,json=raceId,proto3" json:"race_id,omitempty"`
	RunnerId             string                 `protobuf:"bytes,2,opt,name=runner_id,json=runnerId,proto3" json:"runner_id,omitempty"`
	PredictedProbability float64                `protobuf:"fixed64,3,opt,name=predicted_probability,json=predictedProbability,proto3" json:"predicted_probability,omitempty"`
	Confidence           float64                `protobuf:"fixed64,4,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Recommendation       string                 `protobuf:"bytes,5,opt,name=recommendation,proto3" json:"recommendation,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SinglePredictionResponse) Reset() {
	*x = SinglePredictionResponse{}
	mi := &file_ml_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SinglePredictionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SinglePredictionResponse) ProtoMessage() {}

func (x *SinglePredictionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ml_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SinglePredictionResponse.ProtoReflect.Descriptor instead.
func (*SinglePredictionResponse) Descriptor() ([]byte, []int) {
	return file_ml_service_proto_rawDescGZIP(), []int{16}
}

func (x *SinglePredictionResponse) GetRaceId() string {
	if x != nil {
		return x.RaceId
	}
	return ""
}

func (x *SinglePredictionResponse) GetRunnerId() string {
	if x != nil {
		return x.RunnerId
	}
	return ""
}

func (x *SinglePredictionResponse) GetPredictedProbability() float64 {
	if x != nil {
		return x.PredictedProbability
	}
	return 0
}

func (x *SinglePredictionResponse) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *SinglePredictionResponse) GetRecommendation() string {
	if x != nil {
		return x.Recommendation
	}
	return ""
}

var File_ml_service_proto protoreflect.FileDescriptor

const file_ml_service_proto_rawDesc = "" +
	"\n" +
	"\x10ml_service.proto\x12\tmlservice\"\xab\x01\n" +
	"\x11PredictionRequest\x12\x17\n" +
	"\arace_id\x18\x01 \x01(\tR\x06raceId\x12\x1f\n" +
	"\vstrategy_id\x18\x02 \x01(\tR\n" +
	"strategyId\x12\x1a\n" +
	"\bfeatures\x18\x03 \x03(\x01R\bfeatures\x12\x1b\n" +
	"\trunner_id\x18\x04 \x01(\tR\brunnerId\x12#\n" +
	"\rmodel_version\x18\x05 \x01(\tR\fmodelVersion\"\xec\x01\n" +
	"\x12PredictionResponse\x12\x17\n" +
	"\arace_id\x18\x01 \x01(\tR\x06raceId\x123\n" +
	"\x15predicted_probability\x18\x02 \x01(\x01R\x14predictedProbability\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x01R\n" +
	"confidence\x12\x1b\n" +
	"\trunner_id\x18\x04 \x01(\tR\brunnerId\x12&\n" +
	"\x0erecommendation\x18\x05 \x01(\tR\x0erecommendation\x12#\n" +
	"\rmodel_version\x18\x06 \x01(\tR\fmodelVersion\"2\n" +
	"\x0fStrategyRequest\x12\x1f\n" +
	"\vstrategy_id\x18\x01 \x01(\tR\n" +
	"strategyId\"\x84\x01\n" +
	"\x10StrategyResponse\x12\x1f\n" +
	"\vstrategy_id\x18\x01 \x01(\tR\n" +
	"strategyId\x12'\n" +
	"\x0fcomposite_score\x18\x02 \x01(\x01R\x0ecompositeScore\x12&\n" +
	"\x0erecommendation\x18\x03 \x01(\tR\x0erecommendation\">\n" +
	"\x0eFeatureRequest\x12,\n" +
	"\x12backtest_result_id\x18\x01 \x01(\tR\x10backtestResultId\"\x94\x01\n" +
	"\x0fFeatureResponse\x12D\n" +
	"\bfeatures\x18\x01 \x03(\v2(.mlservice.FeatureResponse.FeaturesEntryR\bfeatures\x1a;\n" +
	"\rFeaturesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"&\n" +
	"\fHealthStatus\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\a\n" +
	"\x05Empty\"\xc6\x03\n" +
	"\x17BacktestFeedbackRequest\x12\x1f\n" +
	"\vstrategy_id\x18\x01 \x01(\tR\n" +
	"strategyId\x12'\n" +
	"\x0fcomposite_score\x18\x02 \x01(\x01R\x0ecompositeScore\x12!\n" +
	"\fsharpe_ratio\x18\x03 \x01(\x01R\vsharpeRatio\x12\x10\n" +
	"\x03roi\x18\x04 \x01(\x01R\x03roi\x12!\n" +
	"\fmax_drawdown\x18\x05 \x01(\x01R\vmaxDrawdown\x12\x19\n" +
	"\bwin_rate\x18\x06 \x01(\x01R\awinRate\x12#\n" +
	"\rprofit_factor\x18\a \x01(\x01R\fprofitFactor\x12\x1d\n" +
	"\n" +
	"total_bets\x18\b \x01(\x05R\ttotalBets\x12S\n" +
	"\vml_features\x18\t \x03(\v22.mlservice.BacktestFeedbackRequest.MlFeaturesEntryR\n" +
	"mlFeatures\x12\x16\n" +
	"\x06method\x18\n" +
	" \x01(\tR\x06method\x1a=\n" +
	"\x0fMlFeaturesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"o\n" +
	"\x18BacktestFeedbackResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vfeedback_id\x18\x03 \x01(\tR\n" +
	"feedbackId\"\xa2\x04\n" +
	"\x19StrategyGenerationRequest\x12\x1d\n" +
	"\n" +
	"risk_level\x18\x01 \x01(\tR\triskLevel\x12#\n" +
	"\rtarget_return\x18\x02 \x01(\x01R\ftargetReturn\x12,\n" +
	"\x12max_drawdown_limit\x18\x03 \x01(\x01R\x10maxDrawdownLimit\x12 \n" +
	"\fmin_win_rate\x18\x04 \x01(\x01R\n" +
	"minWinRate\x12%\n" +
	"\x0emax_candidates\x18\x05 \x01(\x05R\rmaxCandidates\x12m\n" +
	"\x13aggregated_features\x18\x06 \x03(\v2<.mlservice.StrategyGenerationRequest.AggregatedFeaturesEntryR\x12aggregatedFeatures\x12U\n" +
	"\vtop_metrics\x18\a \x03(\v24.mlservice.StrategyGenerationRequest.TopMetricsEntryR\n" +
	"topMetrics\x1aE\n" +
	"\x17AggregatedFeaturesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\x1a=\n" +
	"\x0fTopMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"Z\n" +
	"\x1aStrategyGenerationResponse\x12<\n" +
	"\n" +
	"strategies\x18\x01 \x03(\v2\x1c.mlservice.GeneratedStrategyR\n" +
	"strategies\"\xdf\x02\n" +
	"\x11GeneratedStrategy\x12\x1f\n" +
	"\vstrategy_id\x18\x01 \x01(\tR\n" +
	"strategyId\x12L\n" +
	"\n" +
	"parameters\x18\x02 \x03(\v2,.mlservice.GeneratedStrategy.ParametersEntryR\n" +
	"parameters\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x01R\n" +
	"confidence\x12'\n" +
	"\x0fexpected_return\x18\x04 \x01(\x01R\x0eexpectedReturn\x12'\n" +
	"\x0fexpected_sharpe\x18\x05 \x01(\x01R\x0eexpectedSharpe\x12*\n" +
	"\x11expected_win_rate\x18\x06 \x01(\x01R\x0fexpectedWinRate\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"^\n" +
	"\x16BatchPredictionRequest\x12D\n" +
	"\vpredictions\x18\x01 \x03(\v2\".mlservice.SinglePredictionRequestR\vpredictions\"\x8c\x01\n" +
	"\x17SinglePredictionRequest\x12\x17\n" +
	"\arace_id\x18\x01 \x01(\tR\x06raceId\x12\x1b\n" +
	"\trunner_id\x18\x02 \x01(\tR\brunnerId\x12\x1f\n" +
	"\vstrategy_id\x18\x03 \x01(\tR\n" +
	"strategyId\x12\x1a\n" +
	"\bfeatures\x18\x04 \x03(\x01R\bfeatures\"`\n" +
	"\x17BatchPredictionResponse\x12E\n" +
	"\vpredictions\x18\x01 \x03(\v2#.mlservice.SinglePredictionResponseR\vpredictions\"\xcd\x01\n" +
	"\x18SinglePredictionResponse\x12\x17\n" +
	"\arace_id\x18\x01 \x01(\tR\x06raceId\x12\x1b\n" +
	"\trunner_id\x18\x02 \x01(\tR\brunnerId\x123\n" +
	"\x15predicted_probability\x18\x03 \x01(\x01R\x14predictedProbability\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x01R\n" +
	"confidence\x12&\n" +
	"\x0erecommendation\x18\x05 \x01(\tR\x0erecommendation2\xc1\x04\n" +
	"\tMLService\x12L\n" +
	"\rGetPrediction\x12\x1c.mlservice.PredictionRequest\x1a\x1d.mlservice.PredictionResponse\x12K\n" +
	"\x10EvaluateStrategy\x12\x1a.mlservice.StrategyRequest\x1a\x1b.mlservice.StrategyResponse\x12D\n" +
	"\vGetFeatures\x12\x19.mlservice.FeatureRequest\x1a\x1a.mlservice.FeatureResponse\x128\n" +
	"\vHealthCheck\x12\x10.mlservice.Empty\x1a\x17.mlservice.HealthStatus\x12a\n" +
	"\x16SubmitBacktestFeedback\x12\".mlservice.BacktestFeedbackRequest\x1a#.mlservice.BacktestFeedbackResponse\x12_\n" +
	"\x10GenerateStrategy\x12$.mlservice.StrategyGenerationRequest\x1a%.mlservice.StrategyGenerationResponse\x12U\n" +
	"\fBatchPredict\x12!.mlservice.BatchPredictionRequest\x1a\".mlservice.BatchPredictionResponseB=Z;github.com/yourusername/clever-better/internal/ml/mlpb;mlpbb\x06proto3"

var (
	file_ml_service_proto_rawDescOnce sync.Once
	file_ml_service_proto_rawDescData []byte
)

func file_ml_service_proto_rawDescGZIP() []byte {
	file_ml_service_proto_rawDescOnce.Do(func() {
		file_ml_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ml_service_proto_rawDesc), len(file_ml_service_proto_rawDesc)))
	})
	return file_ml_service_proto_rawDescData
}

var file_ml_service_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_ml_service_proto_goTypes = []any{
	(*PredictionRequest)(nil),          // 0: mlservice.PredictionRequest
	(*PredictionResponse)(nil),         // 1: mlservice.PredictionResponse
	(*StrategyRequest)(nil),            // 2: mlservice.StrategyRequest
	(*StrategyResponse)(nil),           // 3: mlservice.StrategyResponse
	(*FeatureRequest)(nil),             // 4: mlservice.FeatureRequest
	(*FeatureResponse)(nil),            // 5: mlservice.FeatureResponse
	(*HealthStatus)(nil),               // 6: mlservice.HealthStatus
	(*Empty)(nil),                      // 7: mlservice.Empty
	(*BacktestFeedbackRequest)(nil),    // 8: mlservice.BacktestFeedbackRequest
	(*BacktestFeedbackResponse)(nil),   // 9: mlservice.BacktestFeedbackResponse
	(*StrategyGenerationRequest)(nil),  // 10: mlservice.StrategyGenerationRequest
	(*StrategyGenerationResponse)(nil), // 11: mlservice.StrategyGenerationResponse
	(*GeneratedStrategy)(nil),          // 12: mlservice.GeneratedStrategy
	(*BatchPredictionRequest)(nil),     // 13: mlservice.BatchPredictionRequest
	(*SinglePredictionRequest)(nil),    // 14: mlservice.SinglePredictionRequest
	(*BatchPredictionResponse)(nil),    // 15: mlservice.BatchPredictionResponse
	(*SinglePredictionResponse)(nil),   // 16: mlservice.SinglePredictionResponse
	nil,                                // 17: mlservice.FeatureResponse.FeaturesEntry
	nil,                                // 18: mlservice.BacktestFeedbackRequest.MlFeaturesEntry
	nil,                                // 19: mlservice.StrategyGenerationRequest.AggregatedFeaturesEntry
	nil,                                // 20: mlservice.StrategyGenerationRequest.TopMetricsEntry
	nil,                                // 21: mlservice.GeneratedStrategy.ParametersEntry
}
var file_ml_service_proto_depIdxs = []int32{
	17, // 0: mlservice.FeatureResponse.features:type_name -> mlservice.FeatureResponse.FeaturesEntry
	18, // 1: mlservice.BacktestFeedbackRequest.ml_features:type_name -> mlservice.BacktestFeedbackRequest.MlFeaturesEntry
	19, // 2: mlservice.StrategyGenerationRequest.aggregated_features:type_name -> mlservice.StrategyGenerationRequest.AggregatedFeaturesEntry
	20, // 3: mlservice.StrategyGenerationRequest.top_metrics:type_name -> mlservice.StrategyGenerationRequest.TopMetricsEntry
	12, // 4: mlservice.StrategyGenerationResponse.strategies:type_name -> mlservice.GeneratedStrategy
	21, // 5: mlservice.GeneratedStrategy.parameters:type_name -> mlservice.GeneratedStrategy.ParametersEntry
	14, // 6: mlservice.BatchPredictionRequest.predictions:type_name -> mlservice.SinglePredictionRequest
	16, // 7: mlservice.BatchPredictionResponse.predictions:type_name -> mlservice.SinglePredictionResponse
	0,  // 8: mlservice.MLService.GetPrediction:input_type -> mlservice.PredictionRequest
	2,  // 9: mlservice.MLService.EvaluateStrategy:input_type -> mlservice.StrategyRequest
	4,  // 10: mlservice.MLService.GetFeatures:input_type -> mlservice.FeatureRequest
	7,  // 11: mlservice.MLService.HealthCheck:input_type -> mlservice.Empty
	8,  // 12: mlservice.MLService.SubmitBacktestFeedback:input_type -> mlservice.BacktestFeedbackRequest
	10, // 13: mlservice.MLService.GenerateStrategy:input_type -> mlservice.StrategyGenerationRequest
	13, // 14: mlservice.MLService.BatchPredict:input_type -> mlservice.BatchPredictionRequest
	1,  // 15: mlservice.MLService.GetPrediction:output_type -> mlservice.PredictionResponse
	3,  // 16: mlservice.MLService.EvaluateStrategy:output_type -> mlservice.StrategyResponse
	5,  // 17: mlservice.MLService.GetFeatures:output_type -> mlservice.FeatureResponse
	6,  // 18: mlservice.MLService.HealthCheck:output_type -> mlservice.HealthStatus
	9,  // 19: mlservice.MLService.SubmitBacktestFeedback:output_type -> mlservice.BacktestFeedbackResponse
	11, // 20: mlservice.MLService.GenerateStrategy:output_type -> mlservice.StrategyGenerationResponse
	15, // 21: mlservice.MLService.BatchPredict:output_type -> mlservice.BatchPredictionResponse
	15, // [15:22] is the sub-list for method output_type
	8,  // [8:15] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_ml_service_proto_init() }
func file_ml_service_proto_init() {
	if File_ml_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ml_service_proto_rawDesc), len(file_ml_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ml_service_proto_goTypes,
		DependencyIndexes: file_ml_service_proto_depIdxs,
		MessageInfos:      file_ml_service_proto_msgTypes,
	}.Build()
	File_ml_service_proto = out.File
	file_ml_service_proto_goTypes = nil
	file_ml_service_proto_depIdxs = nil
}
